### ISSUE TITLE
animationDuration not working

### ISSUE THREAD

**Issue by rhals000327** [oigil/dndod#1]
dndod.popup option animationDuration is not working currently. For example, if I give animationDuration:5000 the popup opens/closes at 250 ms but if I close the popup I can't click anything since dndod-wrapper is still alive(wrapper disappears after 5000ms). 
Even though I fix default option prefix in js to other values, it still comes out in 250ms and is still alive for 5000ms.
Below is my source I used for testing. Thanks for making such a cool library. 

```
dndod.popup({
    msg: "글을 정말 삭제하시겠습니까?",
    animationDuration: "5000",
    buttons: [
                {
                    text: "닫기",
                    handler: function(e, popup) {
                        popup.close()
                    }
                },
                {
                    text: "삭제",
                    type: "danger",
                    handler: function(e, popup) {
                        console.log(popup)
                        popup.close()
                        dndod.notice("글이 삭제되었습니다.")
                    }
                },
            ]
});
```

**Comment by oigil** [comment]
@rhals000327 
just pushed the modified code to master branch(v1.0.3).
let me know if issue occurs.

**Comment by rhals000327** [comment]
Just checked it. It has been Fixed!! Thanks !!
